name: flutter_msgs
description: "Byte serialization using msgpack"
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_model:
    path: ../flutter_model
  flutter_msgpack:
    path: ../flutter_msgpack

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
